#!/usr/bin/env python3
"""scanplate.py — scaffold a ready-to-run custom async scanner.

Generates a single-file Python scanner with the production plumbing already
wired: CLI args, bb-common scope gate, Caido proxy default, bounded async
concurrency + rate limiting, retry/backoff, baseline-anchored diff, secure JSON+
rich output with secret redaction, and a time/request cap.

The generated file has placeholders (TODOs) where YOU add the bug's logic.

Usage:
    python3 scanplate.py --name idor_scan --target https://api.example.com \
        --module idor --out ./idor_scan.py

    python3 scanplate.py --name probe --module basic --out ./probe.py

Then edit the generated file: set BASELINE logic, add your probe/match, and run:
    python3 idor_scan.py --url https://api.example.com/users/{id}
"""
from __future__ import annotations

import argparse
import textwrap
from pathlib import Path

BB = "/home/harsh/.config/opencode/skills/bb-common/scripts"

PLUMBING = r'''#!/usr/bin/env python3
"""GENERATED by scanplate.py — edit the TODO sections to add the bug logic.
Safety: scope-gated (bb-common safe_scope.py), proxied through Caido by default,
secrets redacted, rate-limited, time-boxed."""
from __future__ import annotations
import argparse, asyncio, json, random, statistics, sys, time
from pathlib import Path
import httpx

BB = "{BB}"
sys.path.insert(0, BB)
from bb_common import redact, Logger      # noqa: E402
log = Logger("scan", level="info")


def gate(target: str, scope: str | None, exclude: str | None) -> None:
    """Fail-closed scope gate: abort unless target clearly in authorized scope."""
    import subprocess
    if not scope:
        log.error("ABORT: no --scope file provided (fail closed)")
        sys.exit(3)
    cmd = [sys.executable, f"{BB}/safe_scope.py", "--target", target,
           "--scope", scope]
    if exclude:
        cmd += ["--exclude", exclude]
    rc = subprocess.call(cmd)
    if rc != 0:
        log.error("ABORT: target not authorized (fail closed)", rc=rc)
        sys.exit(2)


class Engine:
    def __init__(self, concurrency: int = 20, rps: float = 5.0,
                 timeout: float = 15.0, proxy: str | None = None):
        self.sem = asyncio.Semaphore(concurrency)
        self.min_interval = 1.0 / rps
        self._last = 0.0
        self.client = httpx.AsyncClient(
            timeout=timeout, proxy=proxy if proxy else None,
            follow_redirects=True,
            headers={"User-Agent": "Mozilla/5.0 (research; authorized testing)"},
        )

    async def _rate_limit(self):
        now = asyncio.get_event_loop().time()
        delay = self.min_interval - (now - self._last)
        if delay > 0:
            await asyncio.sleep(delay)
        self._last = asyncio.get_event_loop().time()

    async def fetch(self, method: str, url: str, *, headers=None, json_body=None,
                    attempts: int = 3, allow_status: tuple = (200, 201, 204, 401, 403)):
        async with self.sem:
            for n in range(attempts):
                await self._rate_limit()
                try:
                    r = await self.client.request(method, url, headers=headers, json=json_body)
                    if r.status_code == 429:
                        await asyncio.sleep(max(int(r.headers.get("Retry-After", 5)), 5))
                        continue
                    if r.status_code in allow_status:
                        return r
                    return r
                except (httpx.RequestError, asyncio.TimeoutError):
                    if n == attempts - 1:
                        raise
                    await asyncio.sleep(2 ** n + random.uniform(0, 1))

    async def close(self):
        await self.client.aclose()


def baseline_key(r) -> dict:
    """Stable structural key for baseline-anchored diff (kills false positives)."""
    body = r.text
    return {"status": r.status_code, "len": len(r.content), "fp": hash(body[-2000:])}


def changed(r, base: dict, allowed=()):
    if r.status_code in allowed:
        return False
    same = (r.status_code == base["status"]
            and abs(len(r.content) - base["len"]) < 10
            and hash(r.text[-2000:]) == base["fp"])
    return not same


# ============================ TODO: YOUR LOGIC ================================
# Fill in per the custom-scanner-kit SKILL.md / pattern-library.md.
# Each candidate result should be: {"url":..., "severity":..., "evidence": redacted}
async def scan_one(eng: Engine, target: str, headers: dict):
    """One logical test. Customize this to probe/mutate/compare."""
    r = await eng.fetch("GET", target, headers=headers)
    # Example baseline diff:
    base = {"status": 200, "len": 1024, "fp": hash("example")}
    if changed(r, base):
        log.info("signal candidate", url=target, status=r.status_code)
        return {"url": target, "severity": "INFO", "evidence": redact(r.url.path)}
    return None
# ==============================================================================


async def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--url", required=True, help="target URL (can contain {id} etc)")
    ap.add_argument("--scope", default=None, help="scope file (fail closed w/o)")
    ap.add_argument("--exclude", default=None)
    ap.add_argument("--concurrency", type=int, default=20)
    ap.add_argument("--rps", type=float, default=5.0)
    ap.add_argument("--timeout", type=float, default=15.0)
    ap.add_argument("--proxy", default="http://127.0.0.1:8081", help="Caido proxy")
    ap.add_argument("--max-requests", type=int, default=500, help="time/load cap")
    ap.add_argument("--header", action="append", default=[], help="Name: Value")
    ap.add_argument("--json", dest="as_json", action="store_true")
    a = ap.parse_args()

    gate(a.url, a.scope, a.exclude)
    headers = dict(h.split(":", 1) for h in a.header if ":" in h)
    eng = Engine(a.concurrency, a.rps, a.timeout,
                 None if a.proxy == "none" else a.proxy)
    findings = []
    try:
        # Stream your unit-of-work here; cap by --max-requests.
        seen = 0
        for i in range(a.max_requests):
            # TODO: generate the i-th URL/input here (e.g. a.url.format(id=i))
            f = await scan_one(eng, a.url.format(id=i), headers)
            if f:
                findings.append(f)
            seen += 1
            if seen >= a.max_requests:
                break
    finally:
        await eng.close()

    if a.as_json:
        print(json.dumps({"findings": findings}, indent=2))
    else:
        for f in findings:
            print(f"[{f['severity']}] {f['url']} :: {f.get('evidence', '')}")
        print(f"done: {len(findings)} finding(s)")
    return 0 if not findings else 1


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
'''


def main() -> int:
    ap = argparse.ArgumentParser(description="Scaffold a custom async scanner")
    ap.add_argument("--name", required=True, help="scanner name (file base)")
    ap.add_argument("--out", default=".", help="output dir (default: .)")
    a = ap.parse_args()

    out = Path(a.out) / f"{a.name}.py"
    src = PLUMBING.replace("{BB}", BB)
    out.write_text(src)
    print(f"wrote {out}")
    print("edit the TODO sections, then run with --url / --scope / --proxy")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
