#!/usr/bin/env python3
"""WAF Response Analyzer.

Detect whether an HTTP response is a WAF block page, a soft challenge, or a
genuine application response. Designed to be invoked by ``bypass_403.sh`` when
naive status-code heuristics break down (e.g. WAF returning ``200 OK`` with a
block page body).

Pure standard library: ``urllib``, ``ssl``, ``json``, ``re``, ``argparse``,
``dataclasses``, ``hashlib``, ``statistics``, ``datetime``.

CLI
---

::

    waf_response_analyzer.py --calibrate <url> --output <baseline.json> [--quiet]
    waf_response_analyzer.py --classify --status <N> --body <file> --headers <file>
                             --baseline <baseline.json> --metrics "<code>|<size>|<time>"
                             --format json
    waf_response_analyzer.py --diff <body_a> <body_b>
"""

from __future__ import annotations

import argparse
import dataclasses
import hashlib
import json
import re
import ssl
import statistics
import sys
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from typing import Any


# ---------------------------------------------------------------------------
# Signature database
# ---------------------------------------------------------------------------


class WAFSignatureDB:
    """In-memory database of vendor body/header patterns."""

    VENDORS: list[dict[str, Any]] = [
        {
            "name": "cloudflare",
            "body_patterns": [
                r"cf-challenge-form",
                r"Just a moment\.\.\.",
                r"Attention Required! \| Cloudflare",
                r"Sorry, you have been blocked",
                r"Cloudflare Ray ID:",
                r"Error 1020",
                r"cdn-cgi/challenge-platform",
                r"__cf_chl_tk",
            ],
            "header_patterns": [r"cf-ray", r"__cfduid", r"__cf_bm", r"cf-cache-status"],
        },
        {
            "name": "aws-waf",
            "body_patterns": [
                r"<AccessDenied>",
                r"Request blocked.*AWS",
                r"Generated by cloudfront",
                r"<TITLE>ERROR: The request could not be satisfied",
            ],
            "header_patterns": [r"x-amzn-requestid", r"x-amzn-trace-id", r"x-amz-cf-id"],
        },
        {
            "name": "imperva",
            "body_patterns": [
                r"_Incapsula_Resource",
                r"incident ID:",
                r"subject=WAF Block",
                r"iframe.*incident_id",
                r"visid_incap",
            ],
            "header_patterns": [r"incap_ses", r"visid_incap", r"x-cdn: imperva", r"x-iinfo"],
        },
        {
            "name": "akamai",
            "body_patterns": [
                r"AkamaiGHost",
                r"Reference #[0-9]",
                r"ak-bm-",
                r"Access Denied.*You don.t have permission",
            ],
            "header_patterns": [r"akamai-x-", r"akamaighost", r"x-akamai"],
        },
        {
            "name": "f5-bigip",
            "body_patterns": [
                r"The requested URL was rejected",
                r"Please consult with your administrator",
                r"[Ss]upport ID:.*[0-9]{10}",
                r"support_id=[0-9]+",
            ],
            "header_patterns": [r"TS[0-9a-f]{6,}"],
        },
        {
            "name": "modsecurity",
            "body_patterns": [
                r"mod_security",
                r"ModSecurity",
                r"Not Acceptable!",
                r"NAXSI",
            ],
            "header_patterns": [],
        },
        {
            "name": "sucuri",
            "body_patterns": [
                r"Sucuri WebSite Firewall",
                r"Access Denied - Sucuri",
                r"Block reason:",
            ],
            "header_patterns": [r"x-sucuri-id"],
        },
        {
            "name": "fortiweb",
            "body_patterns": [
                r"Powered by Fortinet",
                r"Attack ID:.*[0-9]",
                r"FortiWeb",
            ],
            "header_patterns": [],
        },
        {
            "name": "barracuda",
            "body_patterns": [
                r"Barracuda.*blocked",
                r"BNI__BARRACUDA",
                r"BNWeb",
            ],
            "header_patterns": [r"barra_counter_session"],
        },
        {
            "name": "wallarm",
            "body_patterns": [r"nginx-wallarm", r"Wallarm"],
            "header_patterns": [],
        },
        {
            "name": "360-waf",
            "body_patterns": [r"360WebSafe", r"wangzhan.360.cn"],
            "header_patterns": [],
        },
        {
            "name": "wordfence",
            "body_patterns": [r"Generated by Wordfence", r"Wordfence.*blocked"],
            "header_patterns": [],
        },
    ]

    GENERIC_LOG_ID_PATTERN = (
        r"(?i)(?:log|trace|event|request|error|ref(?:erence)?|incident|support)"
        r"\s*(?:id|number|#)[:\s#]+([a-zA-Z0-9_\-]{6,40})"
    )

    BLOCK_TITLE_KEYWORDS = [
        r"access denied",
        r"request rejected",
        r"blocked",
        r"forbidden",
        r"attention required",
        r"403 forbidden",
        r"security violation",
        r"not acceptable",
    ]

    CHALLENGE_KEYWORDS = [
        r"cf-challenge-form",
        r"Just a moment\.\.\.",
        r"checking your browser",
        r"please enable javascript",
        r"cdn-cgi/challenge-platform",
    ]

    def __init__(self) -> None:
        self._compiled_body: list[tuple[str, list[re.Pattern[str]]]] = []
        self._compiled_headers: list[tuple[str, list[re.Pattern[str]]]] = []
        for vendor in self.VENDORS:
            self._compiled_body.append(
                (
                    vendor["name"],
                    [re.compile(p, re.IGNORECASE | re.DOTALL) for p in vendor["body_patterns"]],
                )
            )
            self._compiled_headers.append(
                (
                    vendor["name"],
                    [re.compile(p, re.IGNORECASE) for p in vendor["header_patterns"]],
                )
            )
        self._title_re = re.compile(
            "|".join(self.BLOCK_TITLE_KEYWORDS), re.IGNORECASE
        )
        self._challenge_re = re.compile(
            "|".join(self.CHALLENGE_KEYWORDS), re.IGNORECASE
        )
        self._generic_log_re = re.compile(self.GENERIC_LOG_ID_PATTERN)

    def match_vendors(self, body: str, headers: str) -> list[str]:
        hits: list[str] = []
        for name, regexes in self._compiled_body:
            if any(rx.search(body) for rx in regexes):
                hits.append(name)
                continue
        for name, regexes in self._compiled_headers:
            if name in hits:
                continue
            if any(rx.search(headers) for rx in regexes):
                hits.append(name)
        # Stable de-dup, preserve first-seen order.
        seen: set[str] = set()
        out: list[str] = []
        for h in hits:
            if h not in seen:
                seen.add(h)
                out.append(h)
        return out

    def has_block_title(self, body: str) -> bool:
        # Look at first 4096 chars only (titles live near top).
        return bool(self._title_re.search(body[:4096]))

    def has_challenge_signal(self, body: str) -> bool:
        return bool(self._challenge_re.search(body[:8192]))

    def generic_log_id(self, body: str) -> str | None:
        m = self._generic_log_re.search(body)
        return m.group(1) if m else None


# ---------------------------------------------------------------------------
# Log ID extraction
# ---------------------------------------------------------------------------


class LogIDExtractor:
    """Extract WAF log/trace identifiers from response body."""

    PATTERNS: dict[str, str] = {
        "cf-ray": r"(?i)(?:cf-ray|cloudflare\s*ray\s*id)[:\s#=]+([0-9a-f]{12,20}(?:-[A-Z]{3})?)",
        "f5-support": r"(?i)support\s*id[:\s#=]+([0-9]{10,30})",
        "akamai-ref": r"(?i)reference\s*#?\s*([0-9a-f.]{6,40})",
        "imperva-incident": r"(?i)incident\s*id[:\s#=]+([0-9\-]{6,40})",
        "aws-request": r"(?i)(?:x-amzn-requestid|request id)[:\s#=]+([A-Z0-9]{16,40})",
        "modsec-rule": r"(?i)\[id\s+\"?([0-9]{4,7})\"?\]",
    }

    def __init__(self, db: WAFSignatureDB) -> None:
        self._db = db
        self._compiled: dict[str, re.Pattern[str]] = {
            k: re.compile(v) for k, v in self.PATTERNS.items()
        }

    def extract(self, body: str) -> dict[str, str | None]:
        out: dict[str, str | None] = {}
        for name, rx in self._compiled.items():
            m = rx.search(body)
            out[name] = m.group(1) if m else None
        out["generic"] = self._db.generic_log_id(body)
        return out


# ---------------------------------------------------------------------------
# Response fingerprint
# ---------------------------------------------------------------------------


HTML_TAG_RE = re.compile(r"<[^>]+>")
BUSINESS_SIGNAL_RE = re.compile(
    r"(?i)(?:csrf[_-]?token|api[_-]?key|user[_-]?id|access[_-]?token|"
    r"refresh[_-]?token|session[_-]?id|\"[a-z_]+\"\s*:\s*\"|<form\s)"
)
BUSINESS_COOKIE_RE = re.compile(
    r"(?i)set-cookie:\s*(?:[^\n=]*?)(?:session|sess|csrf|auth|jwt|sid|token|phpsessid|jsessionid)"
)


def _strip_html(body: str, max_len: int = 500) -> str:
    text = HTML_TAG_RE.sub(" ", body[:8000])
    text = re.sub(r"\s+", " ", text).strip()
    return text[:max_len]


@dataclasses.dataclass
class ResponseFingerprint:
    status_code: int
    body_length: int
    body_preview: str
    vendor_hits: list[str]
    log_ids: dict[str, str | None]
    has_business_signal: bool
    has_business_cookies: bool
    has_block_title: bool
    has_challenge_signal: bool
    response_time_ms: float
    body_sha256: str

    @classmethod
    def build(
        cls,
        body: str,
        headers: str,
        *,
        status_code: int,
        body_length: int,
        response_time_ms: float,
        db: WAFSignatureDB,
        extractor: LogIDExtractor,
    ) -> "ResponseFingerprint":
        vendor_hits = db.match_vendors(body, headers)
        log_ids = extractor.extract(body)
        return cls(
            status_code=status_code,
            body_length=body_length,
            body_preview=_strip_html(body),
            vendor_hits=vendor_hits,
            log_ids=log_ids,
            has_business_signal=bool(BUSINESS_SIGNAL_RE.search(body[:16000])),
            has_business_cookies=bool(BUSINESS_COOKIE_RE.search(headers)),
            has_block_title=db.has_block_title(body),
            has_challenge_signal=db.has_challenge_signal(body),
            response_time_ms=response_time_ms,
            body_sha256=hashlib.sha256(body.encode("utf-8", errors="replace")).hexdigest(),
        )


# ---------------------------------------------------------------------------
# HTTP helpers
# ---------------------------------------------------------------------------


_INSECURE_CTX: ssl.SSLContext | None = None


def _insecure_ssl_context() -> ssl.SSLContext:
    global _INSECURE_CTX
    if _INSECURE_CTX is None:
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE
        _INSECURE_CTX = ctx
    return _INSECURE_CTX


def _http_get(url: str, *, timeout: float = 8.0) -> dict[str, Any]:
    """Fetch a URL with stdlib only. Returns dict with status/body/headers/elapsed_ms."""
    req = urllib.request.Request(
        url,
        headers={
            "User-Agent": "Mozilla/5.0 (compatible; waf-response-analyzer/1.0)",
            "Accept": "*/*",
        },
    )
    started = datetime.now(timezone.utc)
    try:
        with urllib.request.urlopen(
            req, timeout=timeout, context=_insecure_ssl_context()
        ) as resp:
            raw = resp.read()
            body = raw.decode("utf-8", errors="replace")
            headers = "\n".join(f"{k}: {v}" for k, v in resp.headers.items())
            status = resp.status
    except urllib.error.HTTPError as e:
        try:
            raw = e.read() or b""
        except Exception:
            raw = b""
        body = raw.decode("utf-8", errors="replace")
        headers = "\n".join(f"{k}: {v}" for k, v in (e.headers or {}).items())
        status = e.code
    except (urllib.error.URLError, TimeoutError, ssl.SSLError, OSError) as e:
        body = ""
        headers = ""
        status = 0
        elapsed_ms = (datetime.now(timezone.utc) - started).total_seconds() * 1000.0
        return {
            "status": status,
            "body": body,
            "headers": headers,
            "elapsed_ms": elapsed_ms,
            "error": str(e),
        }
    elapsed_ms = (datetime.now(timezone.utc) - started).total_seconds() * 1000.0
    return {
        "status": status,
        "body": body,
        "headers": headers,
        "elapsed_ms": elapsed_ms,
    }


# ---------------------------------------------------------------------------
# Baseline sampler
# ---------------------------------------------------------------------------


class BaselineSampler:
    """Calibrate Block Baseline (BB) and Normal Baseline (NB) for a target."""

    KNOWN_BAD_PROBES = [
        "/?_waftest=%3Cscript%3Ealert(document.cookie)%3C%2Fscript%3E",
        "/?_waftest=%27%20UNION%20SELECT%20password%20FROM%20users--",
        "/?_waftest=../../../../../../etc/passwd",
        "/?_waftest=%24(id)",
    ]
    NORMAL_PATHS = ["/robots.txt", "/favicon.ico", "/", "/.well-known/security.txt"]

    def __init__(self, db: WAFSignatureDB | None = None) -> None:
        self._db = db or WAFSignatureDB()

    @staticmethod
    def _join(base: str, path: str) -> str:
        if not base.startswith(("http://", "https://")):
            base = "http://" + base
        base = base.rstrip("/")
        # If path starts with "/?" we still concatenate; urljoin would mangle it.
        if path.startswith("/"):
            return base + path
        return base + "/" + path

    def _sample(self, url: str) -> dict[str, Any]:
        resp = _http_get(url, timeout=8.0)
        body = resp.get("body", "")
        headers = resp.get("headers", "")
        vendor_hits = self._db.match_vendors(body, headers)
        return {
            "url": url,
            "status": resp.get("status", 0),
            "length": len(body),
            "elapsed_ms": resp.get("elapsed_ms", 0.0),
            "vendor_hits": vendor_hits,
            "has_block_title": self._db.has_block_title(body),
            "body_sha256": hashlib.sha256(body.encode("utf-8", errors="replace")).hexdigest(),
            "error": resp.get("error"),
        }

    def calibrate(self, base_url: str, output_path: str, quiet: bool = False) -> dict[str, Any]:
        bb_samples: list[dict[str, Any]] = []
        for probe in self.KNOWN_BAD_PROBES:
            url = self._join(base_url, probe)
            if not quiet:
                print(f"[calibrate] BB probe -> {url}", file=sys.stderr)
            bb_samples.append(self._sample(url))

        nb_samples: list[dict[str, Any]] = []
        for path in self.NORMAL_PATHS:
            url = self._join(base_url, path)
            if not quiet:
                print(f"[calibrate] NB probe -> {url}", file=sys.stderr)
            nb_samples.append(self._sample(url))

        # Block baseline summary.
        bb_lengths = [s["length"] for s in bb_samples if s["length"] > 0]
        try:
            bb_median = int(statistics.median(bb_lengths)) if bb_lengths else 0
        except statistics.StatisticsError:
            bb_median = 0
        vendor_counter: dict[str, int] = {}
        for s in bb_samples:
            for v in s["vendor_hits"]:
                vendor_counter[v] = vendor_counter.get(v, 0) + 1
        bb_vendor = max(vendor_counter, key=vendor_counter.get) if vendor_counter else None

        common_sha = ""
        sha_counter: dict[str, int] = {}
        for s in bb_samples:
            sha_counter[s["body_sha256"]] = sha_counter.get(s["body_sha256"], 0) + 1
        if sha_counter:
            common_sha = max(sha_counter, key=sha_counter.get)

        block_baseline = {
            "median_length": bb_median,
            "vendor": bb_vendor,
            "sample_lengths": bb_lengths,
            "common_sha256": common_sha,
            "samples": bb_samples,
        }

        # Normal baseline summary.
        nb_lengths = [s["length"] for s in nb_samples if s["length"] > 0]
        try:
            nb_median = int(statistics.median(nb_lengths)) if nb_lengths else 0
        except statistics.StatisticsError:
            nb_median = 0
        has_framework_signal = any(
            s["status"] in (200, 301, 302, 304) and s["length"] > 0 for s in nb_samples
        )
        normal_baseline = {
            "median_length": nb_median,
            "has_framework_signal": has_framework_signal,
            "samples": nb_samples,
        }

        result = {
            "block_baseline": block_baseline,
            "normal_baseline": normal_baseline,
            "calibrated_at": datetime.now(timezone.utc).isoformat(),
            "base_url": base_url,
        }
        try:
            with open(output_path, "w", encoding="utf-8") as fh:
                json.dump(result, fh, indent=2, ensure_ascii=False)
        except OSError as e:
            print(f"[calibrate] failed to write {output_path}: {e}", file=sys.stderr)
            raise
        if not quiet:
            print(f"[calibrate] wrote {output_path}", file=sys.stderr)
        return result


# ---------------------------------------------------------------------------
# Classifier
# ---------------------------------------------------------------------------


EMPTY_BASELINE: dict[str, Any] = {
    "block_baseline": {"median_length": 0, "vendor": None, "sample_lengths": [], "common_sha256": ""},
    "normal_baseline": {"median_length": 0, "has_framework_signal": False},
}


class ResponseClassifier:
    """Compute weighted block-score and verdict."""

    THRESHOLD_BLOCKED = 60
    THRESHOLD_REVIEW = 30

    def classify(
        self,
        fp: ResponseFingerprint,
        baseline: dict[str, Any] | None,
    ) -> dict[str, Any]:
        baseline = baseline or EMPTY_BASELINE
        bb = baseline.get("block_baseline") or {}
        bb_len = int(bb.get("median_length") or 0)
        bb_vendor = bb.get("vendor")

        signals: list[dict[str, Any]] = []
        score = 0

        # 1. Vendor body / header match.
        if fp.vendor_hits:
            score += 60
            signals.append(
                {
                    "name": "vendor_body_match",
                    "value": fp.vendor_hits[0],
                    "weight": 60,
                }
            )

        # 2. Generic log-id (incident/reference/...).
        if fp.log_ids.get("generic"):
            score += 25
            signals.append(
                {
                    "name": "generic_log_id",
                    "value": fp.log_ids["generic"],
                    "weight": 25,
                }
            )

        # 3. Title-like block keyword.
        if fp.has_block_title:
            score += 30
            signals.append({"name": "block_title_keyword", "weight": 30})

        # 4. Length similarity to block baseline.
        length_ratio = 0.0
        if bb_len > 0:
            length_ratio = round(fp.body_length / bb_len, 4) if fp.body_length else 0.0
            if fp.body_length == bb_len:
                score += 70
                signals.append(
                    {"name": "length_equals_bb", "value": bb_len, "weight": 70}
                )
            else:
                delta = abs(fp.body_length - bb_len) / max(bb_len, 1)
                if delta <= 0.05:
                    score += 50
                    signals.append(
                        {
                            "name": "length_within_bb_5pct",
                            "value": round(delta, 4),
                            "weight": 50,
                        }
                    )
                elif delta <= 0.15:
                    score += 20
                    signals.append(
                        {
                            "name": "length_within_bb_15pct",
                            "value": round(delta, 4),
                            "weight": 20,
                        }
                    )

        # 4b. Empty body matching an empty-body block baseline (WAF silent-drop).
        _EMPTY_SHA256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        bb_sha256 = bb.get("common_sha256", "")
        if fp.body_length == 0 and bb_sha256 == _EMPTY_SHA256:
            score += 70
            signals.append(
                {"name": "empty_body_matches_bb_sha256", "weight": 70}
            )

        # 5. Very fast response time (CDN/WAF edge).
        if 0 < fp.response_time_ms < 80:
            score += 10
            signals.append(
                {"name": "fast_response", "value": fp.response_time_ms, "weight": 10}
            )

        # 6. Absence of business cookies / signals.
        if not fp.has_business_cookies:
            score += 5
            signals.append({"name": "no_business_cookies", "weight": 5})
        if not fp.has_business_signal:
            score += 5
            signals.append({"name": "no_business_signal", "weight": 5})

        # 7. Status-code adjustment: real backend errors lean against "blocked".
        #    These statuses indicate the request reached the backend past the WAF
        #    edge. Treat them as a positive bypass signal only when no vendor
        #    signature has fired — otherwise the vendor signature dominates.
        backend_status_codes = {401, 500, 502, 503}
        if fp.status_code in backend_status_codes:
            if not any(("vendor" in s.get("name", "") or "signature" in s.get("name", "")) for s in signals):
                score += 20
                signals.append({"name": "backend_status_reached", "weight": 20})

        # 8. Challenge-page signal (Cloudflare JS challenge, etc.) -- treat as
        #    blocked but flag separately.
        is_challenge = fp.has_challenge_signal
        if is_challenge and not any(s["name"] == "vendor_body_match" for s in signals):
            score += 30
            signals.append({"name": "challenge_signal", "weight": 30})

        # Verdict.
        if score >= self.THRESHOLD_BLOCKED:
            verdict = "blocked"
        elif score >= self.THRESHOLD_REVIEW:
            verdict = "needs_review"
        else:
            verdict = "bypassed"

        # Reason -- human readable.
        reason_parts: list[str] = []
        if fp.vendor_hits:
            reason_parts.append(f"matched vendor signature ({', '.join(fp.vendor_hits)})")
        if bb_len > 0 and length_ratio:
            reason_parts.append(
                f"body length {fp.body_length} vs block baseline {bb_len} (ratio {length_ratio})"
            )
        if fp.has_block_title:
            reason_parts.append("title contains block keyword")
        if fp.log_ids.get("generic"):
            reason_parts.append(f"log id detected ({fp.log_ids['generic']})")
        if is_challenge:
            reason_parts.append("challenge-page signal present")
        if fp.status_code in {401, 500, 502, 503}:
            reason_parts.append(f"status {fp.status_code} suggests backend response")
        if not reason_parts:
            reason_parts.append("no strong block signals detected")

        # Pick best vendor: explicit hits beat baseline-derived.
        waf_vendor = fp.vendor_hits[0] if fp.vendor_hits else bb_vendor

        return {
            "verdict": verdict,
            "score": score,
            "reason": "; ".join(reason_parts),
            "status_code": fp.status_code,
            "body_length": fp.body_length,
            "block_baseline_length": bb_len,
            "length_ratio": length_ratio,
            "waf_vendor": waf_vendor,
            "is_challenge": is_challenge,
            "signals": signals,
            "extracted_ids": fp.log_ids,
            "body_preview": fp.body_preview,
            "body_sha256": fp.body_sha256,
        }


# ---------------------------------------------------------------------------
# Diff helper
# ---------------------------------------------------------------------------


_TOKEN_RE = re.compile(r"[A-Za-z0-9_]{3,}")


def _tokens(text: str) -> set[str]:
    return set(_TOKEN_RE.findall(text.lower()))


def diff_bodies(a: str, b: str) -> dict[str, Any]:
    la, lb = len(a), len(b)
    length_diff = lb - la
    length_ratio = round(lb / la, 4) if la else 0.0

    a_lines = {ln.strip() for ln in a.splitlines() if ln.strip()}
    b_lines = {ln.strip() for ln in b.splitlines() if ln.strip()}
    common_lines = a_lines & b_lines
    total_lines = a_lines | b_lines
    line_overlap = round(len(common_lines) / max(len(total_lines), 1), 4)

    a_tokens = _tokens(a)
    b_tokens = _tokens(b)
    common_tokens = a_tokens & b_tokens
    union_tokens = a_tokens | b_tokens
    token_overlap = round(len(common_tokens) / max(len(union_tokens), 1), 4)

    return {
        "length_a": la,
        "length_b": lb,
        "length_diff": length_diff,
        "length_ratio_b_over_a": length_ratio,
        "line_overlap_jaccard": line_overlap,
        "token_overlap_jaccard": token_overlap,
        "sha256_a": hashlib.sha256(a.encode("utf-8", errors="replace")).hexdigest(),
        "sha256_b": hashlib.sha256(b.encode("utf-8", errors="replace")).hexdigest(),
        "identical": a == b,
    }


# ---------------------------------------------------------------------------
# I/O helpers
# ---------------------------------------------------------------------------


def _read_text(path: str | None) -> str:
    if not path:
        return ""
    if path == "/dev/null":
        return ""
    try:
        with open(path, "rb") as fh:
            data = fh.read()
        return data.decode("utf-8", errors="replace")
    except FileNotFoundError:
        return ""
    except OSError as e:
        print(f"[warn] could not read {path}: {e}", file=sys.stderr)
        return ""


def _load_baseline(path: str | None) -> dict[str, Any]:
    if not path:
        return EMPTY_BASELINE
    try:
        with open(path, "r", encoding="utf-8") as fh:
            data = json.load(fh)
        if not isinstance(data, dict):
            return EMPTY_BASELINE
        data.setdefault("block_baseline", EMPTY_BASELINE["block_baseline"])
        data.setdefault("normal_baseline", EMPTY_BASELINE["normal_baseline"])
        return data
    except (FileNotFoundError, json.JSONDecodeError):
        return EMPTY_BASELINE
    except OSError as e:
        print(f"[warn] could not load baseline {path}: {e}", file=sys.stderr)
        return EMPTY_BASELINE


def _parse_metrics(metrics: str | None) -> tuple[int, int, float]:
    """Parse "code|size|time" with safe defaults."""
    if not metrics:
        return 0, 0, 0.0
    parts = metrics.split("|")
    try:
        code = int(parts[0]) if len(parts) > 0 and parts[0] else 0
    except ValueError:
        code = 0
    try:
        size = int(parts[1]) if len(parts) > 1 and parts[1] else 0
    except ValueError:
        size = 0
    try:
        t = float(parts[2]) if len(parts) > 2 and parts[2] else 0.0
    except ValueError:
        t = 0.0
    # curl reports time in seconds; convert to ms.
    if t and t < 50:
        t = t * 1000.0
    return code, size, t


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def _format_human(result: dict[str, Any]) -> str:
    lines = [
        f"verdict       : {result['verdict']}",
        f"score         : {result['score']}",
        f"status_code   : {result['status_code']}",
        f"body_length   : {result['body_length']}",
        f"bb_length     : {result['block_baseline_length']}",
        f"length_ratio  : {result['length_ratio']}",
        f"waf_vendor    : {result['waf_vendor']}",
        f"is_challenge  : {result['is_challenge']}",
        f"reason        : {result['reason']}",
        "signals       :",
    ]
    for s in result["signals"]:
        lines.append(f"  - {s}")
    lines.append("extracted_ids :")
    for k, v in result["extracted_ids"].items():
        lines.append(f"  - {k}: {v}")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="waf_response_analyzer.py",
        description="Classify HTTP responses as WAF block / bypass / needs review.",
    )
    parser.add_argument("--calibrate", metavar="URL", help="calibrate baseline against URL")
    parser.add_argument("--output", metavar="PATH", help="baseline output path (with --calibrate)")
    parser.add_argument("--quiet", action="store_true", help="suppress progress output")

    parser.add_argument("--classify", action="store_true", help="classify a single response")
    parser.add_argument("--status", type=int, default=0, help="HTTP status code")
    parser.add_argument("--body", metavar="PATH", help="response body file")
    parser.add_argument("--headers", metavar="PATH", help="response headers file (or /dev/null)")
    parser.add_argument("--baseline", metavar="PATH", help="baseline JSON path")
    parser.add_argument(
        "--metrics",
        metavar="CODE|SIZE|TIME",
        help="pipe-delimited metrics from curl (code|size|time)",
    )
    parser.add_argument(
        "--format", choices=["json", "human"], default="human", help="output format"
    )

    parser.add_argument(
        "--diff",
        nargs=2,
        metavar=("BODY_A", "BODY_B"),
        help="compare two body files and print similarity summary",
    )

    args = parser.parse_args(argv)

    db = WAFSignatureDB()
    extractor = LogIDExtractor(db)

    # --diff mode.
    if args.diff:
        a_text = _read_text(args.diff[0])
        b_text = _read_text(args.diff[1])
        report = diff_bodies(a_text, b_text)
        print(json.dumps(report, indent=2, ensure_ascii=False))
        return 0

    # --calibrate mode.
    if args.calibrate:
        if not args.output:
            parser.error("--calibrate requires --output PATH")
        sampler = BaselineSampler(db)
        try:
            sampler.calibrate(args.calibrate, args.output, quiet=args.quiet)
        except Exception as e:  # noqa: BLE001 -- top-level CLI safety
            print(f"[calibrate] error: {e}", file=sys.stderr)
            return 2
        return 0

    # --classify mode.
    if args.classify:
        body = _read_text(args.body)
        headers = _read_text(args.headers)
        baseline = _load_baseline(args.baseline)
        metric_code, metric_size, metric_time = _parse_metrics(args.metrics)

        status_code = args.status or metric_code
        body_length = metric_size if metric_size > 0 else len(body)
        response_time_ms = metric_time

        fp = ResponseFingerprint.build(
            body,
            headers,
            status_code=status_code,
            body_length=body_length,
            response_time_ms=response_time_ms,
            db=db,
            extractor=extractor,
        )
        classifier = ResponseClassifier()
        result = classifier.classify(fp, baseline)

        if args.format == "json":
            print(json.dumps(result, indent=2, ensure_ascii=False))
        else:
            print(_format_human(result))
        return 0

    parser.print_help(sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
